services:
  ati:
    build:
      context: .
      dockerfile: Dockerfile
    image: ati_ft_driver:latest
    network_mode: host
    ipc: host
    tty: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - ./ros2/src/netft_rdt_driver/config:/workspace/src/netft_rdt_driver/config
    privileged: true
    command: ros2 launch netft_rdt_driver ft_bringup.launch.py